#!/bin/bash
# Vibe Coding Environment Bootstrapper v2.0

echo "Initializing PTHEA Architecture..."

# 1. 建立原子化技能庫 (The Knowledge Substrate)
mkdir -p skills/{00-core,01-patterns,99-evolution}
touch skills/00-core/README.md
echo "# Core Architecture Standards" > skills/00-core/standards.md

# 2. 建立智能體配置目錄 (Agent Brains)
mkdir -p.agent/{roles,workflows,rules}

# 3. 建立進化層 (Evolution Layer)
# _base 是穩定的，community 是變異的
mkdir -p skills/01-patterns/_base
mkdir -p skills/01-patterns/community

# 4. 生成憲法文件 (Constitution)
# 這是 SSOT (Single Source of Truth)
cat <<EOF > AGENTS.md
# VIBE CODING CONSTITUTION (v2.0)
> Enforcement Level: STRICT
> Scope: Global

## 1. Zero-Trust Architecture
All code generated by Team A (Gemini) is considered "Untrusted" until validated by Team B (Claude).
- **Team A**: Authorized to Generate, Propose, and Test.
- **Team B**: Authorized to Approve, Merge, and Define Rules.

## 2. The Evolution Imperative
If a mistake is repeated twice, it MUST be documented.
- Team B is responsible for updating \`skills/\` when patterns emerge.
- Team A must ALWAYS read \`skills/\` before starting a task.

## 3. Safety Invariants
- NO hardcoded secrets.
- NO direct production database deletion.
- ALL public APIs must have type definitions.
EOF

echo "Environment ready. Please proceed to configure MCP servers."
